package com.minsu.guardapp.core.update

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The update manifest, served as a static JSON file beside the APK.
 *
 * A bare APK URL carries no version information — the app cannot tell whether the file at the
 * far end is newer without downloading all of it first — so this small document sits next to it
 * and says what is there. It is generated by `./gradlew packageUpdate` from `version.properties`
 * and the built APK, never written by hand, so it cannot disagree with the file it describes.
 *
 * Optional fields are defaulted so that adding a key later is not a breaking change: an old
 * build reading a newer manifest ignores what it does not recognise, which matters because the
 * whole point of this file is to be read by builds that are out of date.
 */
@JsonClass(generateAdapter = true)
data class UpdateManifestDto(
    /** Compared against [com.minsu.guardapp.BuildConfig.VERSION_CODE]. The only ordering that counts. */
    @Json(name = "version_code") val versionCode: Int,
    /** Shown to the guard. Never compared — "0.10.0" sorts before "0.9.0" as a string. */
    @Json(name = "version_name") val versionName: String,
    @Json(name = "apk_url") val apkUrl: String,
    /** Lowercase hex. Absent means the download cannot be verified, which is allowed but weaker. */
    @Json(name = "sha256") val sha256: String? = null,
    /**
     * Builds older than this cannot talk to the server correctly any more, so they are blocked
     * rather than merely nudged. Defaults to 0 — no floor — so a manifest that omits it never
     * locks anyone out by accident.
     */
    @Json(name = "min_supported_version_code") val minSupportedVersionCode: Int = 0,
    @Json(name = "release_notes") val releaseNotes: String? = null,
    @Json(name = "size_bytes") val sizeBytes: Long? = null,
)

/** A newer build, as the UI needs it. */
data class AppUpdate(
    val versionCode: Int,
    val versionName: String,
    val apkUrl: String,
    val sha256: String?,
    val releaseNotes: String?,
    val sizeBytes: Long?,
)

fun UpdateManifestDto.toAppUpdate() = AppUpdate(
    versionCode = versionCode,
    versionName = versionName,
    apkUrl = apkUrl,
    sha256 = sha256?.trim()?.lowercase()?.takeIf { it.isNotEmpty() },
    releaseNotes = releaseNotes?.trim()?.takeIf { it.isNotEmpty() },
    sizeBytes = sizeBytes?.takeIf { it > 0 },
)

sealed interface UpdateStatus {
    /** Not checked yet, or the check failed. Shows nothing: silence is the safe default. */
    data object Unknown : UpdateStatus

    data object UpToDate : UpdateStatus

    /** Newer build available. Dismissible — the guard decides when. */
    data class Available(val update: AppUpdate) : UpdateStatus

    /** Installed build is below the manifest's floor. Blocking; dismissal does not apply. */
    data class Required(val update: AppUpdate) : UpdateStatus
}
